### ISSUE TITLE
Doesn't work with 1.0?

### ISSUE THREAD

**Issue by Geobert** [karlmacklin/tackleautorun#2] opened 2020-08-24 21:23 UTC
Hi!

I may missing something but I don't know if it works with Factorio 1.0. What are mouse 5 and mouse 4? And how can we rebind the used keys in the mod? Can't see anything in "Mods settings" panel.

**Comment by karlmacklin** [comment] 2020-08-24 21:46
Hey there, I haven't had time yet to try with 1.0. I'll make sure to fix that soon, sometime this week if not tomorrow tuesday.

Mouse 4 and 5 are your mouse buttons. Left click button is mouse 1, right click is mouse 2. Mouse 3 is usually scrollwheel click, but depends on your mouse. Just like mouse 4 and mouse 5, which in my case on my mouse are the thumb buttons. You might have these at all, thus you'll have to rebind them.

Not sure if they maybe show up under regular key bind panel further down below regular binds? I can check while I check for 1.0 compatibility.

**Comment by Geobert** [comment] 2020-08-25 07:30
Thanks for your answer! I've just tested, and it works once I rebind the default keys 👍

**Comment by karlmacklin** [comment] 2020-08-25 07:39
Good to hear - enjoy resting your finger ligaments! :D

**Comment by Geobert** [comment] 2020-08-26 18:48
There are some issue though: sometime, it stops for no reason (not pressing any key or mouse button) so you might need to test a bit yourself ^^'

**Comment by karlmacklin** [comment] 2020-09-05 15:09
I've tested the plugin as I updated it for version 1.0.0, and it seems to be working exactly as before.

I'm closing this issue. If you have any reproducible steps to something not working please let me know.

**Closed as completed by karlmacklin** 2020-09-05 15:09 UTC
